require 'yaml'

current_dir    = File.dirname(File.expand_path(__FILE__))
configs        = YAML.load_file("#{current_dir}/config.yaml")
vagrant_config = configs['env']

Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.build_dir = vagrant_config['build_dir']
    d.ports = ["vagrant_config['ports']['ext_ssh_port']:22"]
    d.has_ssh = true
  end
end
